import React, { useEffect } from 'react';

export default function TermsPrivacyModal({ isOpen, onClose, initialTab = 'terms' }) {
  const [tab, setTab] = React.useState(initialTab);

  useEffect(() => {
    setTab(initialTab);
  }, [initialTab]);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape' && isOpen) {
        onClose();
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onClose]);

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-150">
      <div
        className="fixed inset-0"
        onClick={onClose}
        aria-hidden="true"
      />

      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="terms-modal-title"
        className="relative w-full max-w-2xl bg-white rounded-xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[85vh] z-10 animate-in zoom-in-95 duration-150"
      >
        {/* Header */}
        <div className="p-4 sm:px-6 border-b border-slate-200 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-navy-900 text-white flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-[18px]">verified_user</span>
            </div>
            <div>
              <h2 id="terms-modal-title" className="text-sm sm:text-base font-bold text-slate-900">
                PhishGuard AI — Legal & Privacy Policy
              </h2>
              <p className="text-[11px] font-mono text-slate-500">
                MDP Academic Capstone Defense Framework
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-md text-slate-400 hover:text-slate-700 hover:bg-slate-100 transition"
            aria-label="Close dialog"
          >
            <span className="material-symbols-outlined text-[20px]">close</span>
          </button>
        </div>

        {/* Tab Switcher */}
        <div className="flex border-b border-slate-200 bg-slate-50/70 px-6 pt-2">
          <button
            type="button"
            onClick={() => setTab('terms')}
            className={`pb-2.5 px-3 text-xs font-semibold border-b-2 transition ${
              tab === 'terms'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-800'
            }`}
          >
            Terms & Conditions
          </button>
          <button
            type="button"
            onClick={() => setTab('privacy')}
            className={`pb-2.5 px-3 text-xs font-semibold border-b-2 transition ${
              tab === 'privacy'
                ? 'border-blue-600 text-blue-700'
                : 'border-transparent text-slate-500 hover:text-slate-800'
            }`}
          >
            Privacy Policy
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-6 overflow-y-auto space-y-4 text-xs text-slate-600 leading-relaxed font-sans">
          {tab === 'terms' ? (
            <>
              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  1. Academic & Research Purpose
                </h3>
                <p>
                  PhishGuard AI is an applied cybersecurity intelligence platform developed as an MDP Capstone project. It provides automated multi-agent evaluation of suspicious emails, URLs, and messages for threat triage and educational awareness.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  2. Acceptable Use Policy
                </h3>
                <p>
                  You agree to use this platform solely for defensive security analysis, academic validation, and user security education. You agree not to submit live malware binaries, weaponized payloads, or execute malicious activities targeting third parties.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  3. Multi-Agent Verdict Disclaimers
                </h3>
                <p>
                  Threat scores and Bayesian classifications generated by the Text, URL, and Sender agents are statistical estimations. PhishGuard AI does not replace dedicated enterprise SOC monitoring or human forensic review.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  4. Account Security
                </h3>
                <p>
                  You are responsible for maintaining the confidentiality of your account credentials. Passwords are securely hashed using salted PBKDF2 with SHA-256 and are never stored in plaintext.
                </p>
              </div>
            </>
          ) : (
            <>
              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  1. Information We Collect
                </h3>
                <p>
                  We collect account credentials (email address, full name, selected role) and submitted suspicious text snippets, email headers, or solitary URLs submitted for multi-agent threat analysis.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  2. Password & Credential Security
                </h3>
                <p>
                  User passwords are cryptographically hashed using PBKDF2-HMAC-SHA256 with 100,000 rounds and random 16-byte cryptographic salts. Passwords and raw secrets are never logged, never transmitted in URLs, and never stored in plaintext.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  3. Ingestion & RAG Memory Retention
                </h3>
                <p>
                  Submitted content is processed locally to extract structural indicators (sender domain, URL features, lexical tokens) and stored in the local SQLite incident database for forensic review and vector similarity matching.
                </p>
              </div>

              <div>
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 font-mono mb-1">
                  4. Cookies & Persistent Sessions
                </h3>
                <p>
                  PhishGuard AI uses standard JWT tokens for session verification. Persistent sessions (30 days) are strictly opt-in via the "Remember me" option. No non-essential advertising or tracking cookies are used.
                </p>
              </div>
            </>
          )}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-end">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-xs font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md transition shadow-xs"
          >
            I Understand
          </button>
        </div>
      </div>
    </div>
  );
}
